# 全球50大主流新闻媒体源定义
# 按地区+影响力组织，包含RSS feed地址

NEWS_SOURCES = [
    # ===== 国际通讯社 =====
    {"name": "Reuters", "name_cn": "路透社", "region": "Global",
     "rss": "https://www.reuters.com/tools/rss", "url": "https://www.reuters.com",
     "lang": "en", "focus": ["World", "Economy", "Politics"]},
    {"name": "Associated Press", "name_cn": "美联社", "region": "Global",
     "rss": "https://rsshub.app/apnews", "url": "https://apnews.com",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "BBC News", "name_cn": "BBC新闻", "region": "Global",
     "rss": "https://feeds.bbci.co.uk/news/world/rss.xml", "url": "https://www.bbc.com/news",
     "lang": "en", "focus": ["World", "Politics", "Technology", "Science"]},
    {"name": "CNN", "name_cn": "CNN", "region": "Global",
     "rss": "http://rss.cnn.com/rss/edition.rss", "url": "https://www.cnn.com",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "Al Jazeera English", "name_cn": "半岛电视台", "region": "Global",
     "rss": "https://www.aljazeera.com/xml/rss/all.xml", "url": "https://www.aljazeera.com",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "France 24", "name_cn": "法国24台", "region": "Global",
     "rss": "https://www.france24.com/en/rss", "url": "https://www.france24.com",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "Deutsche Welle", "name_cn": "德国之声", "region": "Global",
     "rss": "https://rss.dw.com/rdf/rss-en-all", "url": "https://www.dw.com",
     "lang": "en", "focus": ["World", "Politics", "Culture"]},
    {"name": "Euronews", "name_cn": "欧洲新闻台", "region": "Global",
     "rss": "https://www.euronews.com/rss", "url": "https://www.euronews.com",
     "lang": "en", "focus": ["World", "Economy"]},

    # ===== 北美 =====
    {"name": "The New York Times", "name_cn": "纽约时报", "region": "North America",
     "rss": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", "url": "https://www.nytimes.com",
     "lang": "en", "focus": ["World", "Politics", "Economy", "Technology"]},
    {"name": "The Washington Post", "name_cn": "华盛顿邮报", "region": "North America",
     "rss": "https://feeds.washingtonpost.com/rss/world", "url": "https://www.washingtonpost.com",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "The Wall Street Journal", "name_cn": "华尔街日报", "region": "North America",
     "rss": "https://feeds.a.dj.com/rss/RSSWorldNews.xml", "url": "https://www.wsj.com",
     "lang": "en", "focus": ["Economy", "World"]},
    {"name": "Bloomberg", "name_cn": "彭博社", "region": "North America",
     "rss": "https://feeds.bloomberg.com/markets/news.rss", "url": "https://www.bloomberg.com",
     "lang": "en", "focus": ["Economy", "Technology"]},
    {"name": "NPR", "name_cn": "美国国家公共广播", "region": "North America",
     "rss": "https://feeds.npr.org/1001/rss.xml", "url": "https://www.npr.org",
     "lang": "en", "focus": ["World", "Politics", "Culture"]},
    {"name": "Los Angeles Times", "name_cn": "洛杉矶时报", "region": "North America",
     "rss": "https://www.latimes.com/rss2.0", "url": "https://www.latimes.com",
     "lang": "en", "focus": ["World", "Politics", "Culture"]},
    {"name": "USA Today", "name_cn": "今日美国", "region": "North America",
     "rss": "https://rssfeeds.usatoday.com/usatoday-NewsTopStories", "url": "https://www.usatoday.com",
     "lang": "en", "focus": ["World", "Politics", "Sports"]},
    {"name": "NBC News", "name_cn": "NBC新闻", "region": "North America",
     "rss": "https://feeds.nbcnews.com/nbcnews/public/news", "url": "https://www.nbcnews.com",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "ABC News", "name_cn": "ABC新闻", "region": "North America",
     "rss": "https://abcnews.go.com/abcnews/topstories", "url": "https://abcnews.go.com",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "CBS News", "name_cn": "CBS新闻", "region": "North America",
     "rss": "https://www.cbsnews.com/latest/rss/main", "url": "https://www.cbsnews.com",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "The Economist", "name_cn": "经济学人", "region": "North America",
     "rss": "https://www.economist.com/feeds/print-sections/77/international.xml", "url": "https://www.economist.com",
     "lang": "en", "focus": ["Economy", "World", "Politics"]},
    {"name": "TIME", "name_cn": "时代周刊", "region": "North America",
     "rss": "https://feeds.feedburner.com/time/topstories", "url": "https://time.com",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "Forbes", "name_cn": "福布斯", "region": "North America",
     "rss": "https://www.forbes.com/real-time/feed2/", "url": "https://www.forbes.com",
     "lang": "en", "focus": ["Economy", "Technology"]},
    {"name": "The Guardian US", "name_cn": "卫报(美国)", "region": "North America",
     "rss": "https://www.theguardian.com/world/rss", "url": "https://www.theguardian.com/us",
     "lang": "en", "focus": ["World", "Politics", "Environment"]},

    # ===== 欧洲 =====
    {"name": "The Guardian UK", "name_cn": "卫报(英国)", "region": "Europe",
     "rss": "https://www.theguardian.com/uk/rss", "url": "https://www.theguardian.com/uk",
     "lang": "en", "focus": ["World", "Politics", "Environment", "Culture"]},
    {"name": "The Telegraph", "name_cn": "每日电讯报", "region": "Europe",
     "rss": "https://www.telegraph.co.uk/rss.xml", "url": "https://www.telegraph.co.uk",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "The Independent", "name_cn": "独立报", "region": "Europe",
     "rss": "https://www.independent.co.uk/news/world/rss", "url": "https://www.independent.co.uk",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "Financial Times", "name_cn": "金融时报", "region": "Europe",
     "rss": "https://www.ft.com/rss/home", "url": "https://www.ft.com",
     "lang": "en", "focus": ["Economy", "World"]},
    {"name": "Le Monde", "name_cn": "世界报", "region": "Europe",
     "rss": "https://www.lemonde.fr/en/rss/une.xml", "url": "https://www.lemonde.fr",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "El Pais", "name_cn": "国家报", "region": "Europe",
     "rss": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada", "url": "https://elpais.com",
     "lang": "en", "focus": ["World", "Politics", "Culture"]},
    {"name": "Der Spiegel", "name_cn": "明镜周刊", "region": "Europe",
     "rss": "https://www.spiegel.de/international/index.rss", "url": "https://www.spiegel.de",
     "lang": "en", "focus": ["World", "Politics"]},
    {"name": "The Irish Times", "name_cn": "爱尔兰时报", "region": "Europe",
     "rss": "https://www.irishtimes.com/arc/outboundfeeds/rss/", "url": "https://www.irishtimes.com",
     "lang": "en", "focus": ["World", "Politics"]},

    # ===== 亚太 =====
    {"name": "South China Morning Post", "name_cn": "南华早报", "region": "Asia",
     "rss": "https://www.scmp.com/rss/4/feed", "url": "https://www.scmp.com",
     "lang": "en", "focus": ["World", "Asia", "Politics"]},
    {"name": "The Straits Times", "name_cn": "海峡时报", "region": "Asia",
     "rss": "https://www.straitstimes.com/news/world/rss", "url": "https://www.straitstimes.com",
     "lang": "en", "focus": ["World", "Asia"]},
    {"name": "The Japan Times", "name_cn": "日本时报", "region": "Asia",
     "rss": "https://www.japantimes.co.jp/feed/topstories", "url": "https://www.japantimes.co.jp",
     "lang": "en", "focus": ["World", "Asia", "Politics"]},
    {"name": "Nikkei Asia", "name_cn": "日经亚洲", "region": "Asia",
     "rss": "https://asia.nikkei.com/rss/feed", "url": "https://asia.nikkei.com",
     "lang": "en", "focus": ["Economy", "Asia", "Technology"]},
    {"name": "The Hindu", "name_cn": "印度教徒报", "region": "Asia",
     "rss": "https://www.thehindu.com/news/international/feeder/default.rss", "url": "https://www.thehindu.com",
     "lang": "en", "focus": ["World", "Asia", "Politics"]},
    {"name": "Times of India", "name_cn": "印度时报", "region": "Asia",
     "rss": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "url": "https://timesofindia.indiatimes.com",
     "lang": "en", "focus": ["World", "Asia"]},
    {"name": "Korea Herald", "name_cn": "韩国先驱报", "region": "Asia",
     "rss": "https://www.koreaherald.com/common/rss/rss_news.php", "url": "https://www.koreaherald.com",
     "lang": "en", "focus": ["World", "Asia", "Politics"]},
    {"name": "The Asahi Shimbun", "name_cn": "朝日新闻英文版", "region": "Asia",
     "rss": "https://www.asahi.com/rss/index_en.xml", "url": "https://www.asahi.com",
     "lang": "en", "focus": ["World", "Asia"]},

    # ===== 中国主流媒体 =====
    {"name": "Xinhua News", "name_cn": "新华社", "region": "China",
     "rss": "https://english.news.cn/rss/world.xml", "url": "https://english.news.cn",
     "lang": "en", "focus": ["World", "China", "Politics"]},
    {"name": "CCTV News", "name_cn": "央视新闻", "region": "China",
     "rss": "https://news.cctv.com/rss/chinageneral.xml", "url": "https://news.cctv.com",
     "lang": "zh", "focus": ["World", "China", "Politics"]},
    {"name": "环球网", "name_cn": "环球网", "region": "China",
     "rss": "https://www.huanqiu.com/rss/world.xml", "url": "https://www.huanqiu.com",
     "lang": "zh", "focus": ["World", "China", "Politics"]},
    {"name": "澎湃新闻", "name_cn": "澎湃新闻", "region": "China",
     "rss": "https://www.thepaper.cn/rss/world.xml", "url": "https://www.thepaper.cn",
     "lang": "zh", "focus": ["World", "China", "Politics"]},
    {"name": "观察者网", "name_cn": "观察者网", "region": "China",
     "rss": "https://www.guancha.cn/rss/news.xml", "url": "https://www.guancha.cn",
     "lang": "zh", "focus": ["World", "China", "Politics"]},
    {"name": "新浪新闻", "name_cn": "新浪新闻", "region": "China",
     "rss": "https://rss.sina.com.cn/news/marquee/roll.xml", "url": "https://news.sina.com.cn",
     "lang": "zh", "focus": ["World", "China", "Technology"]},
    {"name": "腾讯新闻", "name_cn": "腾讯新闻", "region": "China",
     "rss": "https://rss.news.qq.com/news_world", "url": "https://news.qq.com",
     "lang": "zh", "focus": ["World", "China"]},
    {"name": "参考消息", "name_cn": "参考消息", "region": "China",
     "rss": "https://www.cankaoxiaoxi.com/rss/", "url": "https://www.cankaoxiaoxi.com",
     "lang": "zh", "focus": ["World", "China", "Politics"]},

    # ===== 澳洲/大洋洲 =====
    {"name": "Sydney Morning Herald", "name_cn": "悉尼先驱晨报", "region": "Oceania",
     "rss": "https://www.smh.com.au/rss/feed.xml", "url": "https://www.smh.com.au",
     "lang": "en", "focus": ["World", "Australia"]},
    {"name": "The Times (UK)", "name_cn": "泰晤士报", "region": "Europe",
     "rss": "https://www.thetimes.co.uk/rss/news", "url": "https://www.thetimes.co.uk",
     "lang": "en", "focus": ["World", "Politics"]},
]

# 分类系统
CATEGORIES = {
    "World":       {"label": "国际", "color": "#0891b2"},
    "Politics":    {"label": "政治", "color": "#dc2626"},
    "Economy":     {"label": "经济", "color": "#059669"},
    "Technology":  {"label": "科技", "color": "#2563eb"},
    "Science":     {"label": "科学", "color": "#7c3aed"},
    "Environment": {"label": "环境", "color": "#16a34a"},
    "Sports":      {"label": "体育", "color": "#ea580c"},
    "Culture":     {"label": "文化", "color": "#d946ef"},
    "Asia":        {"label": "亚太", "color": "#0e7490"},
    "China":       {"label": "中国", "color": "#be123c"},
    "Australia":   {"label": "澳洲", "color": "#a16207"},
}

CATEGORY_ORDER = ["World", "Politics", "Economy", "Technology", "Science", "Environment", "Sports", "Culture"]

# 分类关键词（标题匹配用）
CATEGORY_KEYWORDS = {
    "Politics": ["president", "election", "vote", "congress", "senate", "parliament",
                 "minister", "government", "diplomat", "sanction", "tariff", "summit",
                 "白宫", "国会", "总统", "选举", "政府", "制裁", "外交", "峰会"],
    "Economy": ["market", "stock", "bond", "trade", "inflation", "gdp", "economic",
                "bank", "interest rate", "currency", "oil price", "recession",
                "经济", "股市", "通胀", "贸易", "利率", "油价", "GDP", "金融"],
    "Technology": ["AI", "artificial intelligence", "chatgpt", "openai", "google",
                   "microsoft", "tesla", "chip", "semiconductor", "quantum",
                   "space", "rocket", "cyber", "data", "algorithm",
                   "人工智能", "芯片", "量子", "航天", "科技", "互联网", "软件"],
    "Science": ["research", "study", "dna", "gene", "climate", "cancer",
                "vaccine", "nasa", "discovery", "evolution",
                "科学", "研究", "基因", "疫苗", "发现", "实验室"],
    "Environment": ["climate", "carbon", "emission", "renewable", "solar", "wind",
                    "wildfire", "flood", "drought", "pollution", "conservation",
                    "环境", "气候", "碳排放", "污染", "生态", "环保"],
    "Sports": ["olympic", "world cup", "championship", "football", "soccer",
               "basketball", "tennis", "nba", "fifa", "medal",
               "体育", "奥运", "世界杯", "冠军", "足球", "篮球", "网球"],
    "Culture": ["film", "movie", "music", "art", "exhibition", "award", "oscar",
                "book", "museum", "heritage", "fashion", "festival",
                "电影", "文化", "艺术", "音乐", "展览", "娱乐"],
}

# Lang mix: 中文源
CHINESE_SOURCES = [s for s in NEWS_SOURCES if s["lang"] == "zh"]
ENGLISH_SOURCES = [s for s in NEWS_SOURCES if s["lang"] == "en"]
ALL_REGIONS = list(dict.fromkeys(s["region"] for s in NEWS_SOURCES))  # 有序去重
